# Site
repository: ktnani/ktnani.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Koushik Tirumanyam
title: Student at Bradley University, Peoria and Intern at VirtuSense Technologies
email: koushik.t29@gmail.com
website: https://ktnani.github.io/
website_title: Web Profile (CV)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: ktnani
linkedin_username: koushik-reddy-6976581a0

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: |
  My name is Koushik and I am currently studying <mark>Masters in Computer Science</mark> at <mark>Bradley University, Peoria, Illinois</mark>. I am also working as a <mark>Software Engineering Intern</mark> at <mark>VirtuSense Technologies</mark>.
  I love all things about <mark>data</mark>. The tech-stack that I use for <mark>data analysis</mark> are <mark>Python</mark>, <mark>SQL</mark>, <mark>Numpy</mark>, <mark>Pandas</mark>, <mark>Matlplotlib</mark>, and <mark>Seaborn</mark>. 
  I am open to explore more opportunities in data analysis, data science and machine learning.

content:
  # ------------------
  # Experience section
  # ------------------
  - title: Experience
    layout: list
    content:
      - layout: top-left
        title: VirtuSense Technologies
        sub_title: Software Engineering Intern
        caption: August 2022 - present
        link: https://www.virtusense.ai/
        description: |
          - Achieved a faster way to update the release versions in VIRTUSENSE devices using FLASK (Python framework)
          - Achieved a proficient way to test our products using automation scripts
          - Played an important role in my team to fix bugs in VST ALERT algorithm
          - Part of thinktank to discuss the issues of algorithms and comeup with solutions to eradicate them

      - layout: top-left
        title: Bradley University
        sub_title: Graduate Assistant
        caption: January 2022 - May 2022
        link: https://www.bradley.edu/
        description: |
          - Conduct interactive sessions with students to clear their doubts in their subjects and coding assignments
          - Worked on research work in Machine Learning models
          - Helped my professors in grading exams

  # ----------------
  # Projects section
  # ----------------
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Smart Meters Project
        description: | # this will include new lines to allow paragraphs
          **Smart Meters** is an initiative project for replacing the traditional electricity meters from the government of India which started in 2020. 
          The initiative project started with a few datahubs and smart meters deployment in key cities. As part of the project, we looked into the data 
          from the datahubs, performed data analysis from time to time to observe the trends and usage of the grids and electricity consumption from different areas of the cities.
          The key idea of this initiative project is to understand the financial gains and losses incurring to the government by transcending to smart / digital solultions by 
          moving away from the traditional meters. As a team of data analysts, we reported monthly and quarterly insights so that the local electricity boards 
          efficiently managed the deployment and behavior of the usage from the localities, forecasting the consumption and demand over the time.

          The toolset we used - <mark>Python</mark>, <mark>Jupyter notebooks</mark>, <mark>Pandas</mark>, <mark>Matplotlib</mark>, <mark>Seaborn</mark>.

      - layout: top-left
        title: WIoT Project
        description: |
          WIoT (Weather IoT) is a weather monitoring project that uses IoT to make use of real time data that can be easily accessible over a very wide range of sensors.
          IoT sensors' data from weather and climate changes like temperature, humidity, wind speed, moisture are sent using multiple sensors. 
          These sensors send the data to the IoT hub in the cloud. The data is available through APIs.

          The toolset we used - <mark>Python</mark>, <mark>requests (for fetching API data)</mark>, <mark>Jupyter notebooks</mark>, <mark>Pandas</mark>, <mark>Matplotlib</mark>, <mark>Seaborn</mark>.

  # -----------------
  # Education section
  # -----------------
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Bradley University
        sub_title: Master of Science
        caption: July 2021 - December 2022
        # quote: >
        description: |
          I am currently studying <mark>Master of Science (Computer Science)</mark> at <mark>Bradley University</mark>, Peoria, Illinois. My graduation is due in <mark>December, 2022</mark>.

          The main subjects that I have studied so far are <mark>Software Engineering</mark>, <mark>Software Project Management</mark>, <mark>Database Management Systems</mark>, <mark>Data Science</mark>, <mark>Machine Learning</mark> and <mark>Data Mining</mark>.

      - layout: top-left
        title: JNTU Anantapur
        sub_title: Bachelor of Technology
        caption: 2013 - 2017
        description: |
          I studied <mark>Bachelor of Technology (Electronics and Communications Engineering)</mark> at <mark>Jawaharlal Nehru Technological University</mark>, Anantapur, India.

  # --------------
  # Extras section
  # --------------
  - title: A Little More About Me
    layout: text
    content: |
      In my free time I like to travel whenever possible. I also try to tinker tech things, like to invest myself in learning new technologies and follow IT trends so that I keep up to date with the industry and the market.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
